name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build

  deploy-pages:
    environment:
      name: github-pages
      url: https://racedirector.github.io/ftr-events-sign-up-tracker/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy to Github Pages
        id: pages-deployment
        uses: actions/deploy-pages@v2

  # Uncomment after configuring AWS credentials
  # deploy-s3:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: shallwefootball/s3-upload-action@master
  #       name: Upload S3
  #       id: S3
  #       with:
  #         aws_key_id: ${{ secrets.AWS_KEY_ID }}
  #         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  #         aws_bucket: ${{ secrets.AWS_BUCKET }}
  #         source_dir: "./build"
  #         destination_dir: "./"
